# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  external_url: !secret external_url
  internal_url: !secret internal_url
  whitelist_external_dirs: 
    - '/config/'
  customize: !include customize.yaml
  packages:
    inputs: !include inputs.yaml
    integrations: !include integrations.yaml
    system: !include system.yaml

person: # enable persons manager from UI
group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts
zone: !include zones.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
frontend:
  themes: !include themes.yaml
