wakeup_week_day_panel:
  name: Alarme de semaine
  entities:
    - input_boolean.wakeup_weekday
    - input_datetime.wakeup_weekday_timestart
    - input_datetime.wakeup_weekday_timestop
    
cover_automation_panel:
  name: Automatisation des volets
  entities:
    - input_boolean.cover_automation
    - input_number.cover_day_offset
    - sensor.cover_auto_open
    - input_number.cover_night_offset
    - sensor.cover_auto_close

covers_all_open:
  name: Fenêtre à ouvrir en grand
  entities:
    - cover.salle_a_manger
    - cover.salon_3
    - cover.bureau_fenetre
    - cover.bureau_baie
