############
## SYSTEM ##
############

# internal web server
http:
  use_x_forwarded_for: true
  # You must set the trusted proxy IP address so that Home Assistant will properly accept connections
  # Set this to your NGINX machine IP, or localhost if hosted on the same machine.
  trusted_proxies: !secret http_trusted_proxies

# data rotation
recorder:
  db_url: !secret db_url
  purge_keep_days: 10
  exclude:
    entities:
      - sun.sun # Don't record sun data
      - sensor.date
      - binary_sensor.updater
      - sensor.transmission_active_torrents
      - sensor.transmission_completed_torrents
      - sensor.transmission_download_speed
      - sensor.transmission_paused_torrents
      - sensor.transmission_started_torrents
      - sensor.transmission_current_status
      - switch.transmission_turtle_mode
      - sensor.transmission_upload_speed

# set hassio updater
updater:
  reporting: false
  include_used_components: false

# Activate logs
logger:
  default: info
  
discovery:
  ignore:
#    - google_cast # ignore google cast from my android tv > it doesn't work
#    - glance # ignore glances as it is already defined below > it doesn't work
